In [2]:
import requests
import pandas as pd

url = "https://fantasy.premierleague.com/api/bootstrap-static/"

response = requests.get(url)
print("Status Code:", response.status_code)
data = response.json()
print(data.keys())

Status Code: 200
dict_keys(['chips', 'events', 'game_settings', 'game_config', 'phases', 'teams', 'total_players', 'element_stats', 'element_types', 'elements'])

### Data Dictionary Notes
- 'elements': have information about a player. It has a lot of attributes (name, team, now_cost, etc...)
- 'teams': have information about teams, such as (name, points, win, etc...)
- 'events': Contain info about each gameweek (most captained, most points, etc...)

### 1.How many players are there?

In [3]:
players = pd.DataFrame(data["elements"])
players.shape

(667, 109)

In [4]:
players["id"].head()

0    1
1    2
2    3
3    4
4    5
Name: id, dtype: int64

In [5]:
players[["first_name", "total_points", "now_cost"]].sample(7)

    first_name  total_points  now_cost
560        Leo             0        40
15        Noni             2        62
453     Curtis             0        55
586     Dilane             0        55
506    Patrick            10        58
247     Justin             0        50
23      Viktor             2        71

In [6]:
players.columns[90:]

Index(['ict_index_rank', 'ict_index_rank_type', 'expected_goals_per_90',
       'saves_per_90', 'expected_assists_per_90',
       'expected_goal_involvements_per_90', 'expected_goals_conceded_per_90',
       'goals_conceded_per_90', 'now_cost_rank', 'now_cost_rank_type',
       'form_rank', 'form_rank_type', 'points_per_game_rank',
       'points_per_game_rank_type', 'selected_rank', 'selected_rank_type',
       'starts_per_90', 'clean_sheets_per_90',
       'defensive_contribution_per_90'],
      dtype='str')

In [7]:
players[['web_name', "code"]]

         web_name    code
0            Raya  154561
1    Arrizabalaga  109745
2         Meslier  437495
3         Gabriel  226597
4        J.Timber  445122
..            ...     ...
662        Isidor  437505
663      Methalie  638411
664         Ahoka  696104
665        Fofana  549940
666      J.Angulo  661313

[667 rows x 2 columns]

In [8]:
players.columns[50:61]

Index(['minutes', 'goals_scored', 'assists', 'clean_sheets', 'goals_conceded',
       'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards',
       'red_cards', 'saves'],
      dtype='str')

In [9]:
players["code"].head(3)

0    154561
1    109745
2    437495
Name: code, dtype: int64

In [10]:
players[["team", "team_code"]].sample(7)

     team  team_code
92      3         91
89      3         91
230     7          9
469    15         43
64      2          7
43      2          7
367    12         40

In [11]:
players[["minutes", "goals_scored"]]

     minutes  goals_scored
0        450             0
1          0             0
2          0             0
3        450             0
4        104             0
..       ...           ...
662      117             1
663       90             0
664        0             0
665       60             0
666        0             0

[667 rows x 2 columns]

### df_players DataFrame
- Identity:  id (unique), code (unique), first_name, second_name. (No null values for all of them)
- Team: team, team_code
- Price: price_change_projections, now_cost
- Performance: points_per_game, total_points
- Stats: 'minutes', 'goals_scored', 'assists', 'clean_sheets', 'goals_conceded','own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards',
       'red_cards', 'saves', defensive_contribution

In [12]:
players[["id", "code", "first_name"]].nunique()

id            667
code          667
first_name    494
dtype: int64

- Conclusion: id appears to be the best primary identifier because every player has one and the values are unique.

### 2. How many teams are there?
- What information describes a team?

In [13]:
teams = pd.DataFrame(data["teams"])
teams.shape

(20, 22)

In [14]:
teams["id"]

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
Name: id, dtype: int64

In [57]:
teams['code'].nunique()

20

In [56]:
teams['short_name']

0     ARS
1     AVL
2     BOU
3     BRE
4     BHA
5     CHE
6     COV
7     CRY
8     EVE
9     FUL
10    HUL
11    IPS
12    LEE
13    LIV
14    MCI
15    MUN
16    NEW
17    NFO
18    TOT
19    SUN
Name: short_name, dtype: str

In [16]:
teams.columns

Index(['code', 'draw', 'form', 'id', 'loss', 'name', 'played', 'points',
       'position', 'short_name', 'strength', 'team_division', 'unavailable',
       'win', 'link_url', 'strength_overall_home', 'strength_overall_away',
       'strength_attack_home', 'strength_attack_away', 'strength_defence_home',
       'strength_defence_away', 'pulse_id'],
      dtype='str')

In [17]:
teams["pulse_id"]

0       1
1       2
2     127
3     130
4     131
5       4
6       5
7       6
8       7
9      34
10     41
11      8
12      9
13     10
14     11
15     12
16     23
17     15
18     21
19     29
Name: pulse_id, dtype: int64

In [18]:
teams.iloc[:2, 10:20]

,strength,team_division,unavailable,win,link_url,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home
0,None,None,False,0,,4,5,0,0,0
1,None,None,False,0,,3,3,0,0,0

- Identity: id, name, short_name
- Performance: draw, form, loss, played, points, position, win
- Strength: 'strength_overall_home', 'strength_overall_away',
       'strength_attack_home', 'strength_attack_away', 'strength_defence_home',
       'strength_defence_away'
### Observations:
- 'link_url' is a null column
- 'pulse_id' and 'code' are numbers but no idea what they mean.
- 'unavailable' is all False, need to see what is this
- 'strength' is all None values
- All Performance, strength_* columns: These fields appear to represent dynamic/current-state information and may change as the season progresses.

### Players and Team link

In [19]:
players["team"].isin(teams["id"]).all()

np.True_

In [20]:
mer = pd.merge(players, teams, left_on='team', right_on='id', how='left')
mer["name"].unique()

<StringArray>
[       'Arsenal',    'Aston Villa',    'Bournemouth',      'Brentford',
       'Brighton',        'Chelsea',  'Coventry City', 'Crystal Palace',
        'Everton',         'Fulham',      'Hull City',   'Ipswich Town',
          'Leeds',      'Liverpool',       'Man City',        'Man Utd',
      'Newcastle',  'Nott'm Forest',          'Spurs',     'Sunderland']
Length: 20, dtype: str

- players are linked with teams table via players.team = teams.id

### 3. What information does a gameweek contain?

In [21]:
gameweek = pd.DataFrame(data["events"])
print(gameweek.shape)
print(gameweek.info())

(38, 29)
<class 'pandas.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         38 non-null     int64
 1   name                       38 non-null     str
 2   deadline_time              38 non-null     str
 3   release_time               0 non-null      object
 4   average_entry_score        38 non-null     int64
 5   finished                   38 non-null     bool
 6   data_checked               38 non-null     bool
 7   highest_scoring_entry      5 non-null      float64
 8   deadline_time_epoch        38 non-null     int64
 9   deadline_time_game_offset  38 non-null     int64
 10  highest_score              5 non-null      float64
 11  is_previous                38 non-null     bool
 12  is_current                 38 non-null     bool
 13  is_next                    38 non-null     bool
 14  cup_leagues_created        38 non-null     bool
 15  h2h_ko_matches_created     38 non-null     bool
 16  can_enter                  38 non-null     bool
 17  can_manage                 38 non-null     bool
 18  released                   38 non-null     bool
 19  ranked_count               38 non-null     int64
 20  overrides                  38 non-null     object
 21  chip_plays                 38 non-null     object
 22  most_selected              5 non-null      float64
 23  most_transferred_in        5 non-null      float64
 24  top_element                5 non-null      float64
 25  top_element_info           5 non-null      object
 26  transfers_made             38 non-null     int64
 27  most_captained             5 non-null      float64
 28  most_vice_captained        5 non-null      float64
dtypes: bool(10), float64(7), int64(6), object(4), str(2)
memory usage: 6.1+ KB
None

In [22]:
gameweek.columns

Index(['id', 'name', 'deadline_time', 'release_time', 'average_entry_score',
       'finished', 'data_checked', 'highest_scoring_entry',
       'deadline_time_epoch', 'deadline_time_game_offset', 'highest_score',
       'is_previous', 'is_current', 'is_next', 'cup_leagues_created',
       'h2h_ko_matches_created', 'can_enter', 'can_manage', 'released',
       'ranked_count', 'overrides', 'chip_plays', 'most_selected',
       'most_transferred_in', 'top_element', 'top_element_info',
       'transfers_made', 'most_captained', 'most_vice_captained'],
      dtype='str')

In [23]:
gameweek["deadline_time_epoch"].head(10)

0    1787333400
1    1787938200
2    1788543000
3    1789216200
4    1789752600
5    1791626400
6    1792231200
7    1792776600
8    1793444400
9    1793989800
Name: deadline_time_epoch, dtype: int64

In [24]:
gameweek['overrides'].iloc[4]["element_types"]

[]

In [25]:
gameweek = pd.DataFrame(data["events"])
gameweek[["is_previous", "is_current", "is_next"]].isna().sum()

is_previous    0
is_current     0
is_next        0
dtype: int64

In [26]:
gameweek[["id", "name", "deadline_time", "released"]].head(3)

   id        name         deadline_time  released
0   1  Gameweek 1  2026-08-21T17:30:00Z      True
1   2  Gameweek 2  2026-08-28T17:30:00Z      True
2   3  Gameweek 3  2026-09-04T17:30:00Z      True

In [27]:
gameweek[['id', 'name', 'finished', 'is_previous', 'is_current', 'is_next', 'deadline_time']].head(5)

,id,name,finished,is_previous,is_current,is_next,deadline_time
0,1,Gameweek 1,True,False,False,False,2026-08-21T17:30:00Z
1,2,Gameweek 2,True,False,False,False,2026-08-28T17:30:00Z
2,3,Gameweek 3,True,False,False,False,2026-09-04T17:30:00Z
3,4,Gameweek 4,True,True,False,False,2026-09-12T12:30:00Z
4,5,Gameweek 5,True,False,True,False,2026-09-18T17:30:00Z

In [28]:
gameweek[['most_selected', 'most_transferred_in', 'top_element', 'top_element_info',
       'transfers_made', 'most_captained', 'most_vice_captained']].head(10)

,most_selected,most_transferred_in,top_element,top_element_info,transfers_made,most_captained,most_vice_captained
0,411.0,1.0,115.0,"{'id': 115, 'points': 17}",0,411.0,1.0
1,165.0,115.0,426.0,"{'id': 426, 'points': 23}",11562127,411.0,1.0
2,411.0,399.0,204.0,"{'id': 204, 'points': 15}",27412065,411.0,426.0
3,165.0,40.0,124.0,"{'id': 124, 'points': 17}",24092744,411.0,165.0
4,411.0,480.0,552.0,"{'id': 552, 'points': 17}",18907524,411.0,426.0
5,NaN,NaN,NaN,None,4611571,NaN,NaN
6,NaN,NaN,NaN,None,0,NaN,NaN
7,NaN,NaN,NaN,None,0,NaN,NaN
8,NaN,NaN,NaN,None,0,NaN,NaN
9,NaN,NaN,NaN,None,0,NaN,NaN

- Identity: 'id', 'name'
- Time Fields: 'deadline_time', 'release_time' but its all null
- Stats: 'average_entry_score', 'highest_scoring_entry', 'highest_score', 'most_selected', 'most_transferred_in', 'top_element', 'top_element_info',
       'transfers_made', 'most_captained', 'most_vice_captained'
### Observations:
- 38 gameweeks
- 'finished': marked True if gameweek is done
- 'highest_scoring_entry', 'highest_score': columns that change over time, currently only 5 gameweeks played, so they have 5 non-null values
- 'release_time': all null values, but 'released' has non-null values.
- 'is_previous': mark latest finished gameweek as "True"
- 'is_current': current week is "True"
- 'is_next': coming gameweek is "True"
- 'cup_leagues_created', 'h2h_ko_matches_created': will change over time, especially at the end of the season.
- 'top_element_info': top player performed for each week. A dictionary of 'id' and 'points'
- 'most_captained' & 'most_vice_captained': id of players

### 4. How does a player connect to a position?

In [29]:
positions = pd.DataFrame(data["element_types"])
print(positions.shape)
positions.head()

(4, 13)

,id,plural_name,plural_name_short,singular_name,singular_name_short,squad_select,squad_min_select,squad_max_select,squad_min_play,squad_max_play,ui_shirt_specific,sub_positions_locked,element_count
0,1,Goalkeepers,GKP,Goalkeeper,GKP,2,None,None,1,1,True,[12],73
1,2,Defenders,DEF,Defender,DEF,5,None,None,3,5,False,[],217
2,3,Midfielders,MID,Midfielder,MID,5,None,None,2,5,False,[],298
3,4,Forwards,FWD,Forward,FWD,3,None,None,1,3,False,[],79

- Only 4 rows (1 for each position)
- 'element_count': sums up to 667 (num of players we got from players df)

In [30]:
print(positions.columns)

Index(['id', 'plural_name', 'plural_name_short', 'singular_name',
       'singular_name_short', 'squad_select', 'squad_min_select',
       'squad_max_select', 'squad_min_play', 'squad_max_play',
       'ui_shirt_specific', 'sub_positions_locked', 'element_count'],
      dtype='str')

In [31]:
mer = pd.merge(players, positions, left_on='element_type', right_on='id', how='left')
players["element_type"].isin(positions["id"]).all()

np.True_

- Conclusion: Players are linked to positions using players.element_type and positions.id. The positions table contains four records representing GK, DEF, MID, and FWD.

### 5. How are fixtures represented?

In [32]:
url = "https://fantasy.premierleague.com/api/fixtures/"

response = requests.get(url)
print("Status Code:", response.status_code)
fixt = response.json()

Status Code: 200

In [33]:
fixtures = pd.DataFrame(fixt)
print(fixtures.columns)
print(fixtures.shape)

Index(['code', 'event', 'finished', 'finished_provisional', 'id',
       'kickoff_time', 'minutes', 'provisional_start_time', 'started',
       'team_a', 'team_a_score', 'team_h', 'team_h_score', 'stats',
       'team_h_difficulty', 'team_a_difficulty', 'pulse_id'],
      dtype='str')
(380, 17)

In [34]:
fixtures.head(2)

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id
0,2645195,1,True,True,1,2026-08-21T19:00:00Z,90,False,True,7,0.0,1,3.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",2,5,0
1,2645198,1,True,True,4,2026-08-22T11:30:00Z,90,False,True,16,0.0,11,2.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",4,2,0

In [35]:
fixtures["minutes"].nunique()

2

In [36]:
fixtures["stats"][1]

[{'identifier': 'goals_scored',
  'a': [],
  'h': [{'value': 1, 'element': 279}, {'value': 1, 'element': 586}]},
 {'identifier': 'assists',
  'a': [],
  'h': [{'value': 1, 'element': 290}, {'value': 1, 'element': 295}]},
 {'identifier': 'own_goals', 'a': [], 'h': []},
 {'identifier': 'penalties_saved', 'a': [], 'h': []},
 {'identifier': 'penalties_missed', 'a': [], 'h': []},
 {'identifier': 'yellow_cards',
  'a': [{'value': 1, 'element': 415}],
  'h': [{'value': 1, 'element': 287}, {'value': 1, 'element': 289}]},
 {'identifier': 'red_cards', 'a': [], 'h': []},
 {'identifier': 'saves',
  'a': [{'value': 2, 'element': 412}],
  'h': [{'value': 5, 'element': 572}]},
 {'identifier': 'bonus',
  'a': [],
  'h': [{'value': 3, 'element': 572},
   {'value': 2, 'element': 279},
   {'value': 1, 'element': 586}]},
 {'identifier': 'bps',
  'a': [{'value': 18, 'element': 426},
   {'value': 17, 'element': 162},
   {'value': 15, 'element': 418},
   {'value': 14, 'element': 428},
   {'value': 13, 'element': 43},
   {'value': 13, 'element': 423},
   {'value': 12, 'element': 427},
   {'value': 9, 'element': 429},
   {'value': 8, 'element': 422},
   {'value': 7, 'element': 412},
   {'value': 7, 'element': 432},
   {'value': 6, 'element': 417},
   {'value': 5, 'element': 421},
   {'value': 3, 'element': 435},
   {'value': 2, 'element': 439},
   {'value': -11, 'element': 415}],
  'h': [{'value': 41, 'element': 572},
   {'value': 39, 'element': 279},
   {'value': 35, 'element': 586},
   {'value': 27, 'element': 277},
   {'value': 24, 'element': 282},
   {'value': 23, 'element': 280},
   {'value': 21, 'element': 295},
   {'value': 20, 'element': 290},
   {'value': 11, 'element': 576},
   {'value': 9, 'element': 289},
   {'value': 8, 'element': 286},
   {'value': 4, 'element': 281},
   {'value': 4, 'element': 585},
   {'value': 3, 'element': 285},
   {'value': 3, 'element': 556},
   {'value': 2, 'element': 287}]},
 {'identifier': 'defensive_contribution',
  'a': [{'value': 9, 'element': 162},
   {'value': 6, 'element': 426},
   {'value': 5, 'element': 43},
   {'value': 5, 'element': 422},
   {'value': 4, 'element': 418},
   {'value': 4, 'element': 423},
   {'value': 4, 'element': 427},
   {'value': 3, 'element': 417},
   {'value': 3, 'element': 428},
   {'value': 2, 'element': 421},
   {'value': 1, 'element': 415},
   {'value': 1, 'element': 429},
   {'value': 1, 'element': 432},
   {'value': 1, 'element': 435}],
  'h': [{'value': 21, 'element': 277},
   {'value': 13, 'element': 586},
   {'value': 10, 'element': 286},
   {'value': 9, 'element': 289},
   {'value': 7, 'element': 279},
   {'value': 6, 'element': 282},
   {'value': 6, 'element': 576},
   {'value': 5, 'element': 295},
   {'value': 4, 'element': 585},
   {'value': 3, 'element': 281},
   {'value': 3, 'element': 287},
   {'value': 3, 'element': 290},
   {'value': 2, 'element': 280},
   {'value': 2, 'element': 285}]}]

In [37]:
fixtures["id"].head()

0    1
1    4
2    3
3    5
4    6
Name: id, dtype: int64

In [38]:
fixtures["event"].dropna().isin(gameweek["id"]).all()

np.True_

In [39]:
fixtures["team_h"].isin(teams["id"]).all()

np.True_

In [40]:
fixtures["team_a"].isin(teams["id"]).all()

np.True_

- Game Identity: 'id'
- Gameweek Indentify: 'event', it corresponds to gameweek.id
- Team Identity: ('team_a', 'team_h'): correspond to teams.id, 'team_h_difficulty', 'team_a_difficulty'
- Stats: 'team_*_score', 'stats'

### Observations:
- 'finished': true if match is finished

- 'stats': list of dictionaries. Each dictionary contain 3 keys: 
    - identifiers (1 value) of ('goals_scored', 'assists'. etc...),
    - 'a': list of dictionaries, each dictionary has, 'value' which identify the value (of identifier) & 'element' which is the players.id from before.

### Conclusion: 
- Each fixture belongs to a gameweek through event -> gameweek.id and references two teams through team_h -> teams.id and team_a -> teams.id.

### 6. Player performance per gameweek
- A specific player is passed into the url API, then the data comes back for this particular player.

In [41]:
player_id = players["id"][320]
url = f"https://fantasy.premierleague.com/api/element-summary/{player_id}/"

response = requests.get(url)
print("Status Code:", response.status_code)
per_gw = response.json()
print(per_gw.keys())

Status Code: 200
dict_keys(['fixtures', 'history', 'history_past'])

In [42]:
type(per_gw["history"])

list

In [43]:
len(per_gw["history"])

5

In [44]:
history = pd.DataFrame(per_gw["history"])
history.tail(3)

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,modified,...,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,value,transfers_balance,selected,transfers_in,transfers_out
2,240,25,2,0,True,2026-09-05T16:30:00Z,0,0,3,False,...,0,0.00,0.00,0.00,0.00,50,122,1385,309,187
3,240,33,6,0,False,2026-09-12T14:00:00Z,2,2,4,False,...,0,0.00,0.00,0.00,0.35,50,128,1598,334,206
4,240,46,17,1,False,2026-09-19T14:00:00Z,2,1,5,False,...,0,0.12,0.01,0.13,0.25,50,101,1818,374,273

In [45]:
history.columns

Index(['element', 'fixture', 'opponent_team', 'total_points', 'was_home',
       'kickoff_time', 'team_h_score', 'team_a_score', 'round', 'modified',
       'minutes', 'goals_scored', 'assists', 'clean_sheets', 'goals_conceded',
       'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards',
       'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity',
       'threat', 'ict_index', 'clearances_blocks_interceptions', 'recoveries',
       'tackles', 'defensive_contribution', 'starts', 'expected_goals',
       'expected_assists', 'expected_goal_involvements',
       'expected_goals_conceded', 'value', 'transfers_balance', 'selected',
       'transfers_in', 'transfers_out'],
      dtype='str')

In [46]:
players.columns

Index(['can_transact', 'can_select', 'chance_of_playing_next_round',
       'chance_of_playing_this_round', 'code', 'cost_change_event',
       'cost_change_event_fall', 'cost_change_start', 'cost_change_start_fall',
       'price_change_percent',
       ...
       'now_cost_rank_type', 'form_rank', 'form_rank_type',
       'points_per_game_rank', 'points_per_game_rank_type', 'selected_rank',
       'selected_rank_type', 'starts_per_90', 'clean_sheets_per_90',
       'defensive_contribution_per_90'],
      dtype='str', length=109)

In [47]:
history["selected"]

0    1417
1    1093
2    1385
3    1598
4    1818
Name: selected, dtype: int64

In [48]:
history["fixture"].isin(fixtures["id"]).all()

np.True_

In [49]:
history["round"].isin(fixtures["event"]).all()

np.True_

In [50]:
history["opponent_team"].isin(teams["id"]).all()

np.True_

In [51]:
(history["element"] == player_id).all()

np.True_

### Observations: 
- 'fixture':  matches fixtures.id
- 'round': gameweek.id
- 'opponent_team': team.id 

### Conclusion: 
Each history row represents one player’s performance in one fixture/gameweek. element identifies the player, fixture links to fixtures.id, round corresponds to the gameweek/event, and opponent_team links to teams.id

In [52]:
history_past = pd.DataFrame(per_gw["history_past"])
history_past

,season_name,element_code,start_cost,end_cost,total_points,minutes,goals_scored,assists,clean_sheets,goals_conceded,...,ict_index,clearances_blocks_interceptions,recoveries,tackles,defensive_contribution,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded
0,2020/21,490094,45,45,0,0,0,0,0,0,...,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00
1,2021/22,490094,45,45,4,90,0,0,1,0,...,1.7,0,0,0,0,0,0.00,0.00,0.00,0.00
2,2022/23,490094,45,45,0,0,0,0,0,0,...,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00
3,2023/24,490094,45,44,10,157,0,0,0,7,...,2.1,0,0,0,0,1,0.00,0.00,0.00,4.95
4,2024/25,490094,45,43,22,562,0,1,0,16,...,19.6,0,0,0,111,5,0.23,0.14,0.37,12.25
5,2025/26,490094,50,48,68,1477,0,3,8,18,...,45.9,43,78,68,189,17,0.54,0.71,1.25,24.64

In [53]:
history_past.columns

Index(['season_name', 'element_code', 'start_cost', 'end_cost', 'total_points',
       'minutes', 'goals_scored', 'assists', 'clean_sheets', 'goals_conceded',
       'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards',
       'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity',
       'threat', 'ict_index', 'clearances_blocks_interceptions', 'recoveries',
       'tackles', 'defensive_contribution', 'starts', 'expected_goals',
       'expected_assists', 'expected_goal_involvements',
       'expected_goals_conceded'],
      dtype='str')

In [54]:
players["code"].nunique()

667

In [55]:
players["code"].head(2)

0    154561
1    109745
Name: code, dtype: int64

### Conclusion:
- history_past: Contains the stats from previous season for each season the player was registered in the game. The columns are not by gameweek like 'history'. However, they are summarized by the whole season.